# See: https://github.com/DavidAnson/markdownlint

# Unordered list style
MD004:
  style: dash

# Disable line length for tables
MD013:
  #  line_length: 120
  tables: false

# Ordered list item prefix
MD029:
  style: ordered

# Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# Code block style
MD046:
  style: fenced

# Reference links and images should use a label that is defined
MD052:
  shortcut_syntax: true

# Link and image style
MD054:
  autolink: false
  collapsed: false
  full: false
  inline: false
  url_inline: false
